apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-1
  template:
    metadata:
      labels:
        app: course-1
    spec:
      containers:
      - name: course-1
        image: vengomatto/docker-course-1